name: Build API docs
on:
  repository_dispatch:
    types: build-api-docs
    
  workflow_dispatch:

#  schedule:
#    - cron:  '*/5 * * * *'

jobs:
  build:
    name: apidocs-build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: EchoInformation
        run: ./scripts/update-api-docs.sh 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true